language: rust
rust:
  - stable
  - nightly-2017-03-04
matrix:
  allow_failures:
    - rust: stable 
script:
  - cargo build --verbose
  - cargo build --features="experimental" --verbose
  - make test
