language: rust
rust:
  - stable
  - nightly-2017-04-11
matrix:
  allow_failures:
    - rust: stable
script:
  - cargo build --all --verbose
  - cargo build --all --features="experimental" --verbose
  - make test
