[package]
name = "pumpkindb"
version = "0.1.0"
authors = ["Yurii Rashkovskii <yrashk@gmail.com>"]

[dependencies]
futures = "0.1.10"

[dev-dependencies]
quickcheck = "0.4.1"
quickcheck_macros = "0.4.1"
